development: &defaults
  vkontakte:
    app_id: 3765867
    app_secret: zS6vzGYXyXivZCkBe4dr
  mailru:
    app_id: 709827
    app_secret: cb8815a3cdb1f43fb07418cb86e3354b
  odnoklassniki:
    app_id: 3765867
    app_secret: zS6vzGYXyXivZCkBe4dr

production:
  <<: *defaults

test:
  <<: *defaults